#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npm run lint --workspace=lab1
npm run prettier --workspace=lab1
npm run slint --workspace=lab1

npm run lint --workspace=lab2
npm run prettier --workspace=lab2
npm run slint --workspace=lab2
