name: Format check
on: [pull_request]
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          cache: "npm"
      - run: npm ci && npm run prettier && npm run lint && npm run slint
